# Generated by Django 4.1.4 on 2022-12-26 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreditCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("limit_amount", models.PositiveIntegerField()),
                ("last_close_date", models.DateField(null=True)),
                ("last_exp_date", models.DateField(null=True)),
                ("current_close_date", models.DateField(null=True)),
                ("current_exp_date", models.DateField(null=True)),
                ("next_close_date", models.DateField(null=True)),
                ("next_exp_date", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Period",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.PositiveIntegerField()),
                ("year", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("cc_name", models.CharField(max_length=50)),
                ("total_amount", models.FloatField()),
                ("refund_amount", models.PositiveIntegerField()),
                ("remaining_amount", models.FloatField()),
                ("purchase_date", models.DateField(null=True)),
                ("first_payment_date", models.DateField(null=True)),
                (
                    "credit_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.creditcard",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Installment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("status", models.CharField(max_length=20)),
                ("number", models.PositiveIntegerField()),
                (
                    "period",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="purchases.period",
                    ),
                ),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.purchase",
                    ),
                ),
            ],
        ),
    ]
