# Generated by Django 4.1.4 on 2022-12-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="financing_installments",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
